language: java

before_install:
  – chmod +x gradlew

jdk: oraclejdk17

script:
  - ./gradlew build

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: things-i-need-to-do

after_deploy:
  -  heroku --app integration-tests pg:reset DATABASE_URL --confirm integration-tests
  -  if ! ./gradlew clean integrationTest -Durl=https://integration-tests.herokuapp.com; then travis_terminate 1;