openapi: 3.0.3
info:
  title: ToDo
  description: To Do api
  version: 1.0.0
paths:
  /to-dos:
    get:
      tags:
        - todos
      description: return all of the to do's
      responses:
        '200':
          description: 200 response gives all of to do's
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ToDo'

    post:
      operationId: save
      tags:
        - todos
      description: save a toDo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDo'
      responses:
        '201':
          description: program created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDo'
  /to-dos/{id}:
    delete:
      operationId: delete
      tags:
        - todos
      description: delete a toDo
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: program has successfully deleted the to do
        '404':
          description: to do not found

components:
  schemas:
    ToDo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
